frontend/components/categoryTag/CategoryTag.component.tsx, frontend/components/mainPost/postCard.component.tsx, frontend/pages/post/[id].tsx, frontend/pages/post/create.tsx
=> Fix: 카테고리 태그 

ecosystem.config.js
pm2 설정
https://songjang.tistory.com/11
=> feat: pm2 설정

.github/workflows/main.yml
네이버 클라우드 접속해서
pm2로 프론트 엔드 배포 완료 
연결 주소 : http://49.50.166.134:3000/
=> feat: github action 자동배포 프론트

frontend/components/categoryTag/CategoryTag.component.tsx, frontend/components/categoryTag/CategoryTagItem.component.tsx, frontend/components/createPostForm/createPostForm.component.tsx, frontend/components/header/header.d.ts, frontend/mockData/categoryData.ts, frontend/mockData/postPageData.ts, frontend/package.json, frontend/pages/post/[id].tsx, frontend/styles/Create.module.scss, frontend/styles/PostCard.module.scss, frontend/styles/PostPage.module.scss, frontend/types/auth.ts, frontend/types/posts.ts, frontend/utils/convertEpochStringToLocale.ts, frontend/yarn.lock
#6 
작업 내용 
* 카테고리 스타일링
* 상세 페이지 퍼블리싱
앞으로 할 내용 
* 버튼 로직에 맞게 렌더링
* 메인페이지 카드 카테고리 너무 많이 추가되면 레이아웃 깨짐
* API 생기면 연결하기
=> Feat/post page/#6 모의면접 상세페이지

frontend/components/categoryTag/CategoryTag.component.tsx, frontend/components/categoryTag/CategoryTagItem.component.tsx, frontend/components/createPostForm/createPostForm.component.tsx, frontend/components/header/header.d.ts, frontend/mockData/categoryData.ts, frontend/mockData/postPageData.ts, frontend/package.json, frontend/pages/post/[id].tsx, frontend/styles/Create.module.scss, frontend/styles/PostCard.module.scss, frontend/styles/PostPage.module.scss, frontend/types/auth.ts, frontend/types/posts.ts, frontend/utils/convertEpochStringToLocale.ts, frontend/yarn.lock
* map key 추가 안 한 부분
* Cookie 타입 건드린 것 롤백
=> build 오류 나는 부분 수정

frontend/components/header/header.component.tsx, frontend/components/header/header.d.ts, frontend/components/modal/loginModal.component.tsx, frontend/next.config.js, frontend/pages/api/github.ts, frontend/pages/api/posts.ts, frontend/pages/index.tsx, frontend/pages/post/create.tsx, frontend/states/user.ts, frontend/styles/Header.module.scss, frontend/types/auth.ts
프론트 로그인 버튼 -> 깃허브 로그인 주소 -> 콜백주소 api/github -> 홈페이지로 리다이렉트
쿠키에 정보를 설정해줌
깃허브 닉네임과 프로필 사진을 사용
=> Feat/githyb login/#41 깃허브 로그인 구현

frontend/components/button/interviewJoinButton.tsx, frontend/components/categoryTag/CategoryTag.component.tsx, frontend/components/createPostForm/createPostForm.component.tsx, frontend/components/header/dropDown.tsx, frontend/components/header/header.component.tsx, frontend/components/modal/loginModal.d.ts, frontend/constants/apiKeys.ts, frontend/mockData/postData.ts, frontend/pages/api/github.ts, frontend/pages/api/logout.ts, frontend/pages/post/[id].tsx, frontend/pages/post/create.tsx, frontend/styles/PostPage.module.scss, frontend/styles/_color.scss, frontend/utils/api/getData.ts, frontend/utils/api/logout.ts, frontend/utils/hooks/useCategoryQuery.ts
feat: 로그아웃  구현  #43 
refactor: 
react-query 사용할 때 useHook으로 한 번 감싸는 것 고려 
버튼 컴포넌트들 분리
=> feat: 로그아웃 구현, refactor: useHook, 컴포넌트 분리

backend/src/app.module.ts, backend/src/enum/questionType.enum.ts, backend/src/enum/userInterviewStatus.enum.ts, backend/src/guards/jwtAuth.guard.ts, backend/src/interfaces/user.interface.ts, backend/src/question/dto/create-question.dto.ts, backend/src/question/dto/create-user-question.dto.ts, backend/src/question/dto/update-question.dto.ts, backend/src/question/dto/update-user-question.dto.ts, backend/src/question/question.controller.ts, backend/src/question/question.module.ts, backend/src/question/question.service.ts
- 화상프로그램 접속시 랜덤 질문을 출력하는 API #50 
- 주요 로직
// userId로 캐싱한 값이 있는지 확인(캐싱 로직 추가 필요)
// 0. id -> interview(방정보 가져오기), category 정보 가져오기
// 1. id -> user_interview(참여 유저)
// 2. 면접 분야 심플해당 파트에서 랜덤으로 가져오기
// 3. 출력형태에 맞춰 가공
- 나의 질문 추가/조회/삭제 #55 
- 토큰 확인 후 나의 질문에 추가/조회/삭제하는 로직
추가사항 별도 이슈로 작성
=> Feat/question/#50 랜덤 질문을 출력/#55 나의 질문 추가/조회/삭제

frontend/components/interviewUser/interviewUser.component.tsx, frontend/components/mainFilter/categoryContainer.component.tsx, frontend/components/question/qaContainer.tsx, frontend/components/question/question.d.ts, frontend/components/resume/resume.compoent.tsx, frontend/pages/index.tsx, frontend/pages/question/[id].tsx, frontend/states/user.ts, frontend/styles/Interview.module.scss, frontend/types/category.ts, frontend/types/resume.ts, frontend/utils/hooks/useMainPost.ts
=> Feat/interview program/74

frontend/utils/api/logout.ts, frontend/utils/hooks/useUserDataQuery.ts
get에서 post 요청으로 바꿉니다.
401에러 콘솔에 찍히는 것
https://stackoverflow.com/questions/65700189/how-to-remove-get-401-unauthorized-error-in-react-and-axios
=> fix: logout

frontend/utils/api/logout.ts, frontend/utils/hooks/useUserDataQuery.ts
=> fix: interview 조회

backend/src/user/dto/create-resume.dto.ts, backend/src/user/user.controller.ts, backend/src/user/user.module.ts, backend/src/user/user.service.ts
#105 이력서 API 작성
- 로그인 필수, 쿠키 토큰을 통해서 userId 통해서 접근
토큰 없는 경우
- item에 등록된 itemId아닌 경우 예외처리
- content 빈 경우 예외처리
- 조회
- 삭제
- 삭제 후 조회
- 삭제 불가(다른사람 ID, 없는 번호)
=> feat: my page resume api

frontend/components/button/audioToggleButton.component.tsx, frontend/components/button/interviewJoinButton.component.tsx, frontend/components/button/toolBoxButton.component.tsx, frontend/components/button/videoToggleButton.component.tsx, frontend/components/header/header.component.tsx, frontend/components/mediasoupVideo/mediasoupVideo.component.tsx, frontend/pages/post/[id].tsx, frontend/pages/room/[room].tsx, frontend/styles/Question.module.scss, frontend/styles/room.module.scss
지금 피그마 레이아웃이랑 다름. 로직 적용하면서 피그마 레이아웃 따라갈  예정
mediaVideo 컴포넌트는 리렌더링이 안되게 하는게 맞는 것 같지만, 로직 적용할 때 리렌더링 발생할 것 같아요.
리렌더링 되면 mediasoup boilerplate 코드들이 전부 재 실행 되는지 궁금합니다. 이럴 때 useCallback 같은거 쓰는건가요?
useEffect((),[])에 내부 로직이 있으니 괜찮을 것 같기도 한데, 리렌더링 되면 어떻게 동작할지 잘 모르겠네요.
=> Feat/program/#82 면접 프로그램 적용 파트 2 

backend/src/interview/interview.service.ts
=> fix: (get) interview/:id member 형 변환#126

backend/src/question/question.controller.ts, backend/src/question/question.service.ts
=> feat: 화상프로그램 질문 조회

backend/src/user/user.controller.ts, backend/src/user/user.module.ts, backend/src/user/user.service.ts
=> feat: 신청한 interview 조회

backend/src/interview/interview.controller.ts, backend/src/question/question.controller.ts, backend/src/user/user.controller.ts
=> fix:user,userId이슈보완

frontend/components/myresume/resumeItem.component.tsx, frontend/styles/MypageResume.module.scss, frontend/styles/PostCardMypage.module.scss, frontend/styles/Question.module.scss
=> fix: 스타일 수정

backend/src/question/question.controller.ts, backend/src/question/question.module.ts, backend/src/question/question.service.ts
관련 이슈: #145 
- 최초 종합 질문 목록 요청 시 응답하기 전에 redis에 질문 목록 저장하기
- 재접속 시 redis에 존재하는 질문목록으로 응답하기
- Promise.all로 모든 redis 저장이 완료되기를 기다린다. 
- Promise.all은 this에 의존해서 작동하므로 Promise를 bind 해준다. (this가 Promise를 가리키도록 해야함)
```typescript
// N명의 유저가 각각 M개의 질문을 가지는 것을 모두 redis에 저장
const promises: Promise<number>[][] =
userInterviewQuestionData.questions.map((user) => {
const { userId, userName } = user;
return user.question.map((question) => {
const { type, id, content } = question;
// 피드백 저장과 형식이 같다. 이후 피드백 저장 요청 시 feedback의 내용이 업데이트된다.
return this.redis.hset(
`question:${interviewId}`,
`${userData.id}:${userId}:${type}:${id}`,
JSON.stringify({
fromName: userData.nickname,
toName: userName,
feedback: '',
questionContent: content,
}),
);
});
});
await Promise.all(promises.map(Promise.all.bind(Promise))); …
```
=> redis에서 질문 저장 / 가져오기

backend/src/interview/interview.service.ts
모의면접 상세페이지 유저상태 API 보완 #184 
1. isStart 추가(레디스 정보 바탕으로 추가 되는 것)
2. 해당 interviewId에 해당하는 내용이 없을 때는 오류 반환
=> feat: 인터뷰 정보 조회 isStart 추가

backend/src/question/question.service.ts
#179 isStart 검사 후 질문관리에서 정보 수정 가능여부 체크
=> Feat/interview question/#179

backend/src/enum/userInterviewStatus.enum.ts, backend/src/feedback/feedback.service.ts, backend/src/guards/interview.guard.ts, backend/src/question/question.service.ts
=> Feat/user interview stauts/#194

backend/src/feedback/feedback.controller.ts, backend/src/feedback/feedback.module.ts, backend/src/feedback/feedback.service.ts, backend/src/guards/member.guard.ts
관련 이슈: #124 
- 종합 피드백 조회(GET feedback/:interviewId) 요청 시 면접 멤버가 아닌경우 401에러 응답
=> 종합 피드백 조회 요청 시 면접 멤버가 아닌경우 에러처리

frontend/components/feedback/feedback.component.tsx, frontend/components/feedback/feedbackFilterHeader.component.tsx, frontend/components/feedback/feedbackItem.component.tsx, frontend/components/header/header.component.tsx, frontend/components/mediasoupVideo/mediasoupVideo.component.tsx, frontend/components/modal/loginModal.component.tsx, frontend/components/question/answer.component.tsx, frontend/constants/apiKeys.ts, frontend/pages/room/[room].tsx, frontend/states/feedbackStarted.ts, frontend/states/loginModal.ts, frontend/styles/feedback.module.scss, frontend/styles/room.module.scss, frontend/types/feedback.ts, frontend/utils/api/getFeedbacks.ts, frontend/utils/hooks/useFeeedbackQuery.ts, frontend/utils/hooks/useUserDataQuery.ts, mediaServer/localTestServer.js, mediaServer/server.js
한 것:
* feedback component 추가
* 내가 받은 피드백과, 내가 준 피드백으로 구분
* 피드백 버튼 확인 alert 등 ux
* websocket 연결 -> 호스트가 피드백 가기 할 때 동시 진행 위해
* 전역 상태로 관리
해야할 것 : 별도 이슈로 분리
버그 정리: #200
=> Feat/feedback/#181 피드백 컴포넌트, 피드백 동시 진행

frontend/components/question/qaContainer.component.tsx, frontend/states/user.ts
=> fix: userId 수정

backend/src/user/user.service.ts
- 내 면점 / 내가 신청한 면접 목록(GET user/interview) 응답에 status 속성 추가
- 0: 모집중, 1: 모집마감(면접 시작), 2: 면접종료(피드백 조회까지 진행한 상태)
=> feat: 내 면접 목록 조회api에 면접 상태 추가

frontend/components/feedback/feedback.component.tsx, frontend/components/feedback/feedbackItemRecv.component.tsx, frontend/types/feedback.ts, frontend/utils/hooks/useJoinHandle.ts
=> Feat/interview program/#201 내가 받은 피드백 출력 형식 맞추기 

frontend/styles/Create.module.scss, frontend/styles/MyManage.module.scss, frontend/styles/MypageInterview.module.scss, frontend/styles/MypageQuestion.module.scss, frontend/styles/MypageResume.module.scss, frontend/styles/PostCardMypage.module.scss, frontend/styles/PostPage.module.scss, frontend/styles/Question.module.scss, frontend/styles/Resume.module.scss, frontend/styles/Room.module.scss
=> Fix/css 디테일/#219

frontend/components/boxContainer.tsx, frontend/components/button/interviewManageButton.component.tsx, frontend/components/myManage/postCard.tsx, frontend/styles/BoxContainer.module.scss, frontend/styles/MypageQuestion.module.scss, frontend/styles/Room.module.scss, frontend/styles/globals.css, frontend/utils/hooks/useJoinHandle.ts
=> Fix/scroll 스크롤 커스텀, 면접 상태 (피드백, 신청)
